// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm4ViGOaMcsVbDHRf52fWfrGJ6jICUGXk',
    appId: '1:555501224513:web:bb0db83404fb53b3b3fcc0',
    messagingSenderId: '555501224513',
    projectId: 'stac-just01',
    authDomain: 'stac-just01.firebaseapp.com',
    databaseURL: 'https://stac-just01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stac-just01.appspot.com',
    measurementId: 'G-5RBFD87R57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkCXzVuRUG2ap99RN49haxAbZv-tfy34A',
    appId: '1:555501224513:android:eb7b850d0fe1710db3fcc0',
    messagingSenderId: '555501224513',
    projectId: 'stac-just01',
    databaseURL: 'https://stac-just01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stac-just01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_vDMX4DjGodup26wzEJmytGpxlADYFi8',
    appId: '1:555501224513:ios:3e7cd87fc33d59b6b3fcc0',
    messagingSenderId: '555501224513',
    projectId: 'stac-just01',
    databaseURL: 'https://stac-just01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stac-just01.appspot.com',
    iosClientId: '555501224513-tsf1rjcbsga3papb556eao7c959usnge.apps.googleusercontent.com',
    iosBundleId: 'com.example.stac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_vDMX4DjGodup26wzEJmytGpxlADYFi8',
    appId: '1:555501224513:ios:a6e4bca81daee00eb3fcc0',
    messagingSenderId: '555501224513',
    projectId: 'stac-just01',
    databaseURL: 'https://stac-just01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stac-just01.appspot.com',
    iosClientId: '555501224513-p3lefcebav92pa7m9qnmigd9q6kelagu.apps.googleusercontent.com',
    iosBundleId: 'com.example.stac.RunnerTests',
  );
}
